import { Navbar } from '@/components/Navbar';
import './globals.css'
import { Inter } from "next/font/google";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme='dracula' style={{backgroundColor:'black'}}>
      
      <body 
        className='dark: bg-slate-800'
        suppressHydrationWarning={true}
      >   
        <Navbar />  
        <main className="mx-auto max-w-xl p-4 bg-stone-200 min-h-screen text-black">
         {/* <noscript className="text-white">JavaScript is disabled</noscript> */}
          {children}
        </main>
      </body>
      
    </html>
  )
}
