import './globals.css'
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme='dracula' style={{backgroundColor:'black'}}>
      <body className={inter.className}>{children}</body>
      <noscript className="text-white">JavaScript is disabled</noscript>
    </html>
  )
}
