import './globals.css'
import { Poppins } from 'next/font/google'
import { Header } from './components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'web development, web design, javascript, react, node, angular, vue, html, css',
}

const poppins = Poppins({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main className='container'>{children}</main>  
      </body>
      
    </html>
  )
}
