import './globals.css'
import { Navbar } from './components/Navbar'
import { MyProfle } from './components/MyProfle'

export const metadata = {
  title: "Zhangsan's Blog",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark:bg-slate-800'>
        <Navbar />
        <MyProfle />
        {children}
      </body>
    </html>
  )
}
